namespace KanvasProje.Service.Helpers
{
    public static class TurkishTextRepairHelper
    {
        private static readonly IReadOnlyDictionary<string, string> Replacements = new Dictionary<string, string>
        {
            ["Ã‡"] = "Ç",
            ["Ã§"] = "ç",
            ["Äž"] = "Ğ",
            ["ÄŸ"] = "ğ",
            ["Ä°"] = "İ",
            ["Ä±"] = "ı",
            ["Ã–"] = "Ö",
            ["Ã¶"] = "ö",
            ["Åž"] = "Ş",
            ["ÅŸ"] = "ş",
            ["Ãœ"] = "Ü",
            ["Ã¼"] = "ü",
            ["â‚º"] = "₺",
            ["â€“"] = "-",
            ["â€”"] = "-",
            ["â€™"] = "'",
            ["â€œ"] = "\"",
            ["â€�"] = "\"",
            ["Yaz??l??"] = "Yazılı",
            ["Yaz?l?"] = "Yazılı",
            ["yaz??l??"] = "yazılı",
            ["yaz?l?"] = "yazılı",
            ["Tu??ra"] = "Tuğra",
            ["Tu?ra"] = "Tuğra",
            ["tu??ra"] = "tuğra",
            ["tu?ra"] = "tuğra",
            ["??slami"] = "İslami",
            ["?slami"] = "İslami",
            ["??slam"] = "İslam",
            ["?slam"] = "İslam",
            ["Sanat??"] = "Sanatı",
            ["Sanat?"] = "Sanatı",
            ["sanat??"] = "sanatı",
            ["sanat?"] = "sanatı",
            ["G??rseli"] = "Görseli",
            ["G?rseli"] = "Görseli",
            ["g??rseli"] = "görseli",
            ["g?rseli"] = "görseli",
            ["G??rsel"] = "Görsel",
            ["G?rsel"] = "Görsel",
            ["g??rsel"] = "görsel",
            ["g?rsel"] = "görsel",
            ["Bask??"] = "Baskı",
            ["Bask?"] = "Baskı",
            ["bask??"] = "baskı",
            ["bask?"] = "baskı",
            ["Kad??n"] = "Kadın",
            ["kad??n"] = "kadın",
            ["Farkl??"] = "Farklı",
            ["farkl??"] = "farklı",
            ["Tasar??mlar"] = "Tasarımlar",
            ["tasar??mlar"] = "tasarımlar",
            ["??ehirde"] = "Şehirde",
            ["??ehir"] = "Şehir",
            ["K??rm??z??"] = "Kırmızı",
            ["k??rm??z??"] = "kırmızı",
            ["??emsiyeli"] = "Şemsiyeli",
            ["A??layan"] = "Ağlayan",
            ["a??layan"] = "ağlayan",
            ["K??z"] = "Kız",
            ["k??z"] = "kız",
            ["Temal??"] = "Temalı",
            ["temal??"] = "temalı",
            ["G??l"] = "Gül",
            ["g??l"] = "gül",
            ["g??ller"] = "güller",
            ["Bayku??"] = "Baykuş",
            ["bayku??"] = "baykuş",
            ["Par??al??"] = "Parçalı",
            ["par??al??"] = "parçalı",
            ["Par??a"] = "Parça",
            ["par??a"] = "parça",
            ["??i??ekli"] = "Çiçekli",
            ["??i??ek"] = "Çiçek",
            ["Kurallar??"] = "Kuralları",
            ["kurallar??"] = "kuralları",
            ["D??nya"] = "Dünya",
            ["d??nya"] = "dünya",
            ["Haritas??"] = "Haritası",
            ["haritas??"] = "haritası",
            ["Atat??rk"] = "Atatürk",
            ["K????esi"] = "Köşesi",
            ["S??mb??l"] = "Sümbül",
            ["s??mb??l"] = "sümbül",
            ["A??k"] = "Aşk",
            ["a??k"] = "aşk",
            ["K??pek"] = "Köpek",
            ["k??pek"] = "köpek",
            ["Alt??n"] = "Altın",
            ["alt??n"] = "altın",
            ["A??a??"] = "Ağacı",
            ["a??a??"] = "ağacı",
            ["Fig??rl??"] = "Figürlü",
            ["fig??rl??"] = "figürlü",
            ["??ki"] = "İki",
            ["????"] = "Üç",
            ["D??rt"] = "Dört",
            ["Be??"] = "Beş",
            ["Ki??iye"] = "Kişiye",
            ["ki??iye"] = "kişiye",
            ["??zel"] = "Özel",
            ["i??inde"] = "içinde",
            ["G??zeli"] = "Güzeli",
            ["g??zeli"] = "güzeli",
            ["Sar??"] = "Sarı",
            ["sar??"] = "sarı",
            ["Manzaral??"] = "Manzaralı",
            ["manzaral??"] = "manzaralı",
            ["Ağacıl??"] = "Ağaçlı",
            ["ağacıl??"] = "ağaçlı",
            ["Ağacılar??"] = "Ağaçları",
            ["ağacılar??"] = "ağaçları",
            ["??evrili"] = "Çevrili",
            ["M??zisyen"] = "Müzisyen",
            ["m??zisyen"] = "müzisyen",
            ["Esma??l"] = "Esmaül",
            ["H??sna"] = "Hüsna",
            ["Afrikal??"] = "Afrikalı",
            ["afrikal??"] = "afrikalı",
            ["Fig??r??"] = "Figürü",
            ["fig??r??"] = "figürü",
            ["ill??strasyon"] = "illüstrasyon",
            ["Hi??"] = "Hiç",
            ["hi??"] = "hiç",
            ["??ekici"] = "Çekici",
            ["Odas??"] = "Odası",
            ["odas??"] = "odası",
            ["Bat??m??"] = "Batımı",
            ["bat??m??"] = "batımı",
            ["Z??mr??t"] = "Zümrüt",
            ["Ye??ili"] = "Yeşili",
            ["??hlas"] = "İhlas",
            ["G??n"] = "Gün",
            ["g??n"] = "gün",
            ["G??ky??z??"] = "Gökyüzü",
            ["g??ky??z??"] = "gökyüzü",
            ["Do??a"] = "Doğa",
            ["do??a"] = "doğa",
            ["G??kku??aÜç"] = "Gökkuşağı",
            ["g??kku??aÜç"] = "gökkuşağı",
            ["Osmanl??"] = "Osmanlı",
            ["Da??"] = "Dağ",
            ["Yaprakl??"] = "Yapraklı",
            ["G??kt??rk"] = "Göktürk",
            ["T??rk"] = "Türk",
            ["Muhte??em"] = "Muhteşem",
            ["??stanbul"] = "İstanbul",
            ["R??zgar"] = "Rüzgar",
            ["Gül??"] = "Gülü"
        };

        public static string RepairKnownBrokenTurkish(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            var repaired = value.Trim();
            foreach (var replacement in Replacements)
            {
                repaired = repaired.Replace(replacement.Key, replacement.Value, StringComparison.Ordinal);
            }

            return repaired;
        }

        public static string? RepairKnownBrokenTurkishOrNull(string? value)
        {
            return string.IsNullOrWhiteSpace(value) ? null : RepairKnownBrokenTurkish(value);
        }
    }
}
