// <auto-generated />
using System;
using KanvasProje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanvasProje.Data.Migrations
{
    [DbContext(typeof(KanvasDbContext))]
    [Migration("20260114104848_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KargoTakipNo")
                        .HasColumnType("text");

                    b.Property<string>("MusteriAdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunSecenekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunSecenekId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnaGorselUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CerceveTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaliyetFiyati")
                        .HasColumnType("numeric");

                    b.Property<string>("Olcu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("numeric");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunSecenekleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SiparisDetay", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Siparis", "Siparis")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.UrunSecenek", "UrunSecenek")
                        .WithMany()
                        .HasForeignKey("UrunSecenekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("UrunSecenek");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunSecenek", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany("Secenekler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Siparis", b =>
                {
                    b.Navigation("SiparisDetaylari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.Navigation("Secenekler");
                });
#pragma warning restore 612, 618
        }
    }
}
