// <auto-generated />
using System;
using KanvasProje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanvasProje.Data.Migrations
{
    [DbContext(typeof(KanvasDbContext))]
    [Migration("20260512183057_SlaytlarToDatabase")]
    partial class SlaytlarToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanvasProje.Core.Models.SiteAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BakimModuAktif")
                        .HasColumnType("boolean");

                    b.Property<string>("BakimModuMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BildirimAliciEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalismaSaatleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CookieMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookPixelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaviconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleAnalyticsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IadeHakkiGun")
                        .HasColumnType("integer");

                    b.Property<bool>("IadeTalebiMailBildirimi")
                        .HasColumnType("boolean");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KampanyaMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KargoBedeli")
                        .HasColumnType("numeric");

                    b.Property<string>("KargoFirmasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KargoTakipUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarkaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinterestUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiparisTeslimSuresiGun")
                        .HasColumnType("integer");

                    b.Property<string>("SiteAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteBasligi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StokUyariLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("StokUyarisiMailBildirimi")
                        .HasColumnType("boolean");

                    b.Property<bool>("StoktaYokSatisIzni")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemaRengi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TiktokUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UcretsizKargoLimiti")
                        .HasColumnType("numeric");

                    b.Property<string>("UstBarMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VarsayilanSosyalPaylasimGorseliUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsappNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YeniSiparisMailBildirimi")
                        .HasColumnType("boolean");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SifreSifirlamaGecerlilik")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SifreSifirlamaToken")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.BultenAboneligi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BultenAbonelikleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("UrunId");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.IadeTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AdminNotu")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("IBAN")
                        .HasColumnType("text");

                    b.Property<string>("MusteriId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("IadeTalepleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.IletisimMesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("text");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.KargoFirmasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("GondericiAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GondericiTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GondericiUnvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("TakipUrl")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("KargoFirmalari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AltMetin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<string>("KampanyaEtiketi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentKategoriId")
                        .HasColumnType("integer");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("UrunSiralamaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UstMetin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentKategoriId");

                    b.HasIndex("Slug")
                        .HasFilter("\"Slug\" IS NOT NULL AND \"Slug\" <> ''");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Deger")
                        .HasColumnType("numeric");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KullanilanMiktar")
                        .HasColumnType("integer");

                    b.Property<int>("KullanimLimiti")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinSepetTutari")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kuponlar");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.KurumsalSayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KurumsalSayfalar");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SenTasarla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CercveliMi")
                        .HasColumnType("boolean");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Efekt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("text");

                    b.Property<string>("Olcu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParcaSayisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SepeteEklendi")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("SenTasarla");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<bool>("HatirlatmaGonderildi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TerkEdildi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TerkEdilmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SepetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<string>("CerceveModeli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("MusteriNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecenekAdi")
                        .HasColumnType("text");

                    b.Property<int>("SepetId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("UrunBaslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<string>("UrunResimUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UrunSecenekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunSecenekId");

                    b.ToTable("SepetItems");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("EmailHashKodu")
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaturaDosyaAdi")
                        .HasColumnType("text");

                    b.Property<string>("FaturaDosyaYolu")
                        .HasColumnType("text");

                    b.Property<bool>("FaturaMailGonderildiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FaturaMailGonderimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FaturaYuklendiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FaturaYuklenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("numeric");

                    b.Property<string>("KargoFirmasi")
                        .HasColumnType("text");

                    b.Property<int?>("KargoFirmasiId")
                        .HasColumnType("integer");

                    b.Property<string>("KargoTakipNo")
                        .HasColumnType("text");

                    b.Property<string>("KuponKodu")
                        .HasColumnType("text");

                    b.Property<string>("MusteriAdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("CerceveModeli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusteriNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<int?>("UrunSecenekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunSecenekId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Slayt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AltBaslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("text");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Slaytlar");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AnaGorselUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AnaSayfadaGoster")
                        .HasColumnType("boolean");

                    b.Property<string>("BakimTalimati")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etiketler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FavoriSayisi")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("integer");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("numeric");

                    b.Property<bool>("KampanyaliMi")
                        .HasColumnType("boolean");

                    b.Property<int>("KargoyaVerilisSuresiGun")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KisaAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Maliyet")
                        .HasColumnType("numeric");

                    b.Property<string>("MalzemeBilgisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxSiparisAdedi")
                        .HasColumnType("integer");

                    b.Property<int>("MinSiparisAdedi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OneCikanMi")
                        .HasColumnType("boolean");

                    b.Property<string>("PaketlemeBilgisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SatisSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeoKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("StokDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TahminiTeslimSuresiGun")
                        .HasColumnType("integer");

                    b.Property<string>("TeknikOzellikler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UretimSuresiGun")
                        .HasColumnType("integer");

                    b.Property<string>("UrlYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrunTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YeniUrunMu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("Slug")
                        .HasFilter("\"Slug\" IS NOT NULL AND \"Slug\" <> ''");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunOzellikDegeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunOzellikTanimiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunOzellikTanimiId");

                    b.ToTable("UrunOzellikDegerleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunOzellikTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AlanTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DetaySayfasindaGoster")
                        .HasColumnType("boolean");

                    b.Property<bool>("FiltredeGoster")
                        .HasColumnType("boolean");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secenekler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<bool>("TeknikTablodaGoster")
                        .HasColumnType("boolean");

                    b.Property<string>("UrunTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YardimMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrunTipi", "Kod")
                        .IsUnique();

                    b.ToTable("UrunOzellikTanimlari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltMetin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etiketler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedyaAlani")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedyaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobilResimYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<int?>("UrunSecenekId")
                        .HasColumnType("integer");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrunId", "Sira");

                    b.ToTable("UrunResimleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("CerceveKalinligi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CerceveRengi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CerceveTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Desi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FiyatFarki")
                        .HasColumnType("numeric");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KisilestirmeMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaliyetFiyati")
                        .HasColumnType("numeric");

                    b.Property<string>("MalzemeTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Olcu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnSipariseAcikMi")
                        .HasColumnType("boolean");

                    b.Property<string>("OzelTasarimNotu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParcaSayisi")
                        .HasColumnType("integer");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("numeric");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("integer");

                    b.Property<bool>("TukeninceGizle")
                        .HasColumnType("boolean");

                    b.Property<int>("UretimSuresiGun")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("boolean");

                    b.Property<string>("VaryantSku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunSecenekleri");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnayliMi")
                        .HasColumnType("boolean");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.ZiyaretciLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazBilgisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CihazModeli")
                        .HasColumnType("text");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsletimSistemi")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Metod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferansUrl")
                        .HasColumnType("text");

                    b.Property<string>("Sehir")
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Tarayici")
                        .HasColumnType("text");

                    b.Property<string>("Ulke")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZiyaretciLoglari");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Favori", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.IadeTalebi", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kategori", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Kategori", "ParentKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("ParentKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentKategori");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Sepet", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SepetItem", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Sepet", "Sepet")
                        .WithMany("SepetItems")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.UrunSecenek", "UrunSecenek")
                        .WithMany()
                        .HasForeignKey("UrunSecenekId");

                    b.Navigation("Sepet");

                    b.Navigation("Urun");

                    b.Navigation("UrunSecenek");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Siparis", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.SiparisDetay", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Siparis", "Siparis")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.UrunSecenek", "UrunSecenek")
                        .WithMany()
                        .HasForeignKey("UrunSecenekId");

                    b.Navigation("Siparis");

                    b.Navigation("Urun");

                    b.Navigation("UrunSecenek");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunOzellikDegeri", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany("UrunOzellikleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.UrunOzellikTanimi", "UrunOzellikTanimi")
                        .WithMany("UrunOzellikDegerleri")
                        .HasForeignKey("UrunOzellikTanimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");

                    b.Navigation("UrunOzellikTanimi");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunResim", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany("UrunResimleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunSecenek", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany("UrunSecenek")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Yorum", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KanvasProje.Core.Varliklar.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Sepet", b =>
                {
                    b.Navigation("SepetItems");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Siparis", b =>
                {
                    b.Navigation("SiparisDetaylari");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.Urun", b =>
                {
                    b.Navigation("UrunOzellikleri");

                    b.Navigation("UrunResimleri");

                    b.Navigation("UrunSecenek");
                });

            modelBuilder.Entity("KanvasProje.Core.Varliklar.UrunOzellikTanimi", b =>
                {
                    b.Navigation("UrunOzellikDegerleri");
                });
#pragma warning restore 612, 618
        }
    }
}
