using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanvasProje.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddRoomVisualizations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "RoomVisualizations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AppUserId" text NULL,
    "UrunId" integer NULL,
    "SonucGorselYolu" character varying(300) NOT NULL,
    "UrunGorselYolu" character varying(300) NOT NULL,
    "OturumAnahtari" character varying(80) NULL,
    "Not" character varying(500) NULL,
    "UrunX" numeric NOT NULL DEFAULT 0,
    "UrunY" numeric NOT NULL DEFAULT 0,
    "UrunGenislik" numeric NOT NULL DEFAULT 0,
    "UrunYukseklik" numeric NOT NULL DEFAULT 0,
    "OlusturulmaTarihi" timestamp with time zone NOT NULL DEFAULT NOW(),
    "SilindiMi" boolean NOT NULL DEFAULT false
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_schema = 'public' AND table_name = 'RoomVisualizations'
          AND constraint_name = 'FK_RoomVisualizations_AspNetUsers_AppUserId'
    ) THEN
        ALTER TABLE "RoomVisualizations"
            ADD CONSTRAINT "FK_RoomVisualizations_AspNetUsers_AppUserId"
            FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_schema = 'public' AND table_name = 'RoomVisualizations'
          AND constraint_name = 'FK_RoomVisualizations_Urunler_UrunId'
    ) THEN
        ALTER TABLE "RoomVisualizations"
            ADD CONSTRAINT "FK_RoomVisualizations_Urunler_UrunId"
            FOREIGN KEY ("UrunId") REFERENCES "Urunler"("Id") ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS "IX_RoomVisualizations_AppUserId" ON "RoomVisualizations" ("AppUserId");
CREATE INDEX IF NOT EXISTS "IX_RoomVisualizations_UrunId" ON "RoomVisualizations" ("UrunId");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RoomVisualizations");
        }
    }
}
