using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanvasProje.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddFavoriPriceDropFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
ALTER TABLE "Favoriler" ADD COLUMN IF NOT EXISTS "EskiFiyat" numeric NULL;
ALTER TABLE "Favoriler" ADD COLUMN IF NOT EXISTS "FiyatDustugundaBildir" boolean NOT NULL DEFAULT false;
ALTER TABLE "Favoriler" ADD COLUMN IF NOT EXISTS "SonBildirimTarihi" timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS "HomePageSections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SectionType" integer NOT NULL,
    "Enabled" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "Title" text NOT NULL,
    "Subtitle" text NOT NULL,
    "ViewAllText" text NULL,
    "ViewAllUrl" text NULL,
    "ImageUrl" text NULL,
    "Description" text NULL,
    "ButtonText" text NULL,
    "ButtonUrl" text NULL
);

CREATE TABLE IF NOT EXISTS "HomePageSectionProducts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SectionId" integer NOT NULL,
    "UrunId" integer NOT NULL,
    "SortOrder" integer NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_Adresler_AppUserId" ON "Adresler" ("AppUserId");
CREATE INDEX IF NOT EXISTS "IX_HomePageSectionProducts_SectionId" ON "HomePageSectionProducts" ("SectionId");
CREATE INDEX IF NOT EXISTS "IX_HomePageSectionProducts_UrunId" ON "HomePageSectionProducts" ("UrunId");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_schema = 'public' AND table_name = 'HomePageSectionProducts'
          AND constraint_name = 'FK_HomePageSectionProducts_HomePageSections_SectionId'
    ) THEN
        ALTER TABLE "HomePageSectionProducts"
            ADD CONSTRAINT "FK_HomePageSectionProducts_HomePageSections_SectionId"
            FOREIGN KEY ("SectionId") REFERENCES "HomePageSections"("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_schema = 'public' AND table_name = 'HomePageSectionProducts'
          AND constraint_name = 'FK_HomePageSectionProducts_Urunler_UrunId'
    ) THEN
        ALTER TABLE "HomePageSectionProducts"
            ADD CONSTRAINT "FK_HomePageSectionProducts_Urunler_UrunId"
            FOREIGN KEY ("UrunId") REFERENCES "Urunler"("Id") ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_schema = 'public' AND table_name = 'Adresler'
          AND constraint_name = 'FK_Adresler_AspNetUsers_AppUserId'
    ) THEN
        ALTER TABLE "Adresler"
            ADD CONSTRAINT "FK_Adresler_AspNetUsers_AppUserId"
            FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
    END IF;
END
$$;
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Adresler_AspNetUsers_AppUserId",
                table: "Adresler");

            migrationBuilder.DropTable(
                name: "HomePageSectionProducts");

            migrationBuilder.DropTable(
                name: "HomePageSections");

            migrationBuilder.DropIndex(
                name: "IX_Adresler_AppUserId",
                table: "Adresler");

            migrationBuilder.DropColumn(
                name: "EskiFiyat",
                table: "Favoriler");

            migrationBuilder.DropColumn(
                name: "FiyatDustugundaBildir",
                table: "Favoriler");

            migrationBuilder.DropColumn(
                name: "SonBildirimTarihi",
                table: "Favoriler");
        }
    }
}
