<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KanvasProje.Core\KanvasProje.Core.csproj" />
    <ProjectReference Include="..\KanvasProje.Data\KanvasProje.Data.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Iyzipay" Version="2.1.80" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Hosting" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
